define gift_card_50 = Item("$50 Gift Card", 50, idle_image="gift_card_50")
define emerald_bracelet = Item("Emerald Bracelet", idle_image="emerald_bracelet")
define ruby_choker_necklace = Item("Ruby Choker Necklace", idle_image="ruby_choker_necklace")
define brown_horse_golden_mane = Item("Brown Horse, Golden Mane", idle_image="brown_horse_golden_mane")
define white_horse_black_mane = Item("White Horse, Black Mane", idle_image="white_horse_black_mane")
define sunscreen = Item("Sunscreen")